name: Skippable workflow

on:
  # Runs on PR merge
  push:
    branches:
      - master
      - main
  # Runs on PR: open, reopened, updated
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  job-1:
    # Bypassing this mandatory check should still allow a merge
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo 'this is step 1 from job-1'

      - name: Step 2
        run: |
          echo 'this is step 2 from job-1'
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo 'this is step 1 from job-2'

      - name: Step 2
        run: |
          echo 'this is step 2 from job-2'
