name: Skippable workflow

on:
  # Runs on PR merge
  push:
    branches:
      - master
      - main
  # Runs on PR: open, reopened, updated
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Skip checks and still be mergeable
        id: skip-checks
        run: |
          exit 0

      - name: Step 1
        run: |
          echo 'this is step 1'

      - name: Step 2
        run: |
          echo 'this is step 1'
